# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e01244ad38af43a789ab0b6424e32aa27880296f182cab32bdcfb2ca76f157592349314b78da41a99cc85e740d7338912bdf1d7982a705710ff82bb94befb1d

test:
  secret_key_base: 681cb08120d81ebd0a789a82d025e482dd8c7c09fc8eb1fcec0d47f9e8cf8023c60a2c5647208140b1881fe6b158febb3269cbf94cd4386acb11358321b8535a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
